using System;
using Content.Shared._Amour.Jukebox;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client._Amour.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class AmourJukeboxSongEntry : Control
{
    public AmourJukeboxSong? Song { get; private set; }

    private AmourJukeboxSongEntry()
    {
        RobustXamlLoader.Load(this);
    }

    public AmourJukeboxSongEntry(AmourJukeboxSong song, Action<AmourJukeboxSong> callback) : this()
    {
        Song = song;
        SongNameLabel.Text = Song.SongName;
        PlaySongButton.OnPressed += _ => callback.Invoke(Song);
    }
}
