- type: antag
  id: Vampire
  name: roles-antag-vamire-name
  antagonist: true
  setPreference: true
  objective: roles-antag-vampire-description
  whitelisted: true
  requirements:
  - !type:DiscordLinkRequirement # Amour edit
  - !type:OverallPlaytimeRequirement
    time: 3h
