# ===== Code lockers =====
# Lecter
- type: entity
  parent: [ GunSafeRifleLecterAlertUnlocked, AlertLevelLockRed ]
  id: GunSafeRifleLecterAlertLocked
  suffix: Alert Level Lock

- type: entity
  parent: [ GunSafeRifleLecter ]
  id: GunSafeRifleLecterAlertUnlocked

# Drozd
- type: entity
  parent: [ GunSafeSubMachineGunDrozdAlertUnlocked, AlertLevelLockRed ]
  id: GunSafeSubMachineGunDrozdAlertLocked
  suffix: Alert Level Lock

- type: entity
  parent: [ GunSafeSubMachineGunDrozd ]
  id: GunSafeSubMachineGunDrozdAlertUnlocked

# Enforcer
- type: entity
  parent: [ GunSafeShotgunEnforcerAlertUnlocked, AlertLevelLockRed ]
  id: GunSafeShotgunEnforcerAlertLocked
  suffix: Alert Level Lock

- type: entity
  parent: [ GunSafeShotgunEnforcer ]
  id: GunSafeShotgunEnforcerAlertUnlocked

# Kammerer
- type: entity
  parent: [ GunSafeShotgunKammererAlertUnlocked, AlertLevelLockRed ]
  id: GunSafeShotgunKammererAlertLocked
  suffix: Alert Level Lock

- type: entity
  parent: [ GunSafeShotgunKammerer]
  id: GunSafeShotgunKammererAlertUnlocked

# Wt550
- type: entity
  parent: [ GunSafeSubMachineGunWt550AlertUnlocked, AlertLevelLockRed ]
  id: GunSafeSubMachineGunWt550AlertLocked
  suffix: Alert Level Lock

- type: entity
  parent: [ GunSafeSubMachineGunWt550 ]
  id: GunSafeSubMachineGunWt550AlertUnlocked

# Laser Carabine
- type: entity
  parent: [ GunSafeLaserCarbineAlertUnlocked, AlertLevelLockBlue ]
  id: GunSafeLaserCarbineAlertLocked
  suffix: Alert Level Lock

- type: entity
  parent: [ GunSafeLaserCarbine ]
  id: GunSafeLaserCarbineAlertUnlocked


# ===== Random =====
- type: entity # Pistol
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRandomPistolAlertUnlocked
  name: pistol safe
  suffix: Random, pistol
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRandomPistol

- type: entity # SMG
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRandomSubMachineGunAlertUnlocked
  name: SMG safe
  suffix: Random, SMG
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRandomPistol

- type: entity
  parent: [ GunSafeRandomSubMachineGunAlertUnlocked, AlertLevelLockRed ]
  id: GunSafeRandomSubMachineGunAlertLocked
  suffix: Random, SMG, Alert Level Lock

- type: entity # basic rifles
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRandomLightRifleAlertUnlocked
  name: light rifle safe
  suffix: Random, light rifle
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRandomPistol

- type: entity
  parent: [ GunSafeRandomLightRifleAlertUnlocked, AlertLevelLockRed ]
  id: GunSafeRandomLightRifleAlertLocked
  suffix: Random, light rifle, Alert Level Lock

- type: entity # Special rifles
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRandomHeavyRifleAlertUnlocked
  name: heavy rifle safe
  suffix: Random, heavy rifle
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRandomPistol

- type: entity
  parent: [ GunSafeRandomHeavyRifleAlertUnlocked, AlertLevelLockRed ]
  id: GunSafeRandomHeavyRifleAlertLocked
  suffix: Random, heavy rifle, Alert Level Lock

- type: entity # Basic pump shotguns
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRandomPumpShotgunAlertUnlocked
  name: pump shotgun safe
  suffix: Random, pump shotgun
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRandomPistol

- type: entity
  parent: [ GunSafeRandomPumpShotgunAlertUnlocked, AlertLevelLockRed ]
  id: GunSafeRandomPumpShotgunAlertLocked
  suffix: Random, pump shotgun, Alert Level Lock

- type: entity # Auto shotguns
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRandomAutoShotgunAlertUnlocked
  name: auto shotgun safe
  suffix: Random, auto shotgun
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRandomPistol

- type: entity
  parent: [ GunSafeRandomAutoShotgunAlertUnlocked, AlertLevelLockRed ]
  id: GunSafeRandomAutoShotgunAlertLocked
  suffix: Random, auto shotgun, Alert Level Lock

- type: entity # Laser guns
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRandomLaserCarbineAlertUnlocked
  name: laser carbine safe
  suffix: Random, laser carbine
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRandomPistol

- type: entity
  parent: [ GunSafeRandomLaserCarbineAlertUnlocked, AlertLevelLockBlue ]
  id: GunSafeRandomLaserCarbineAlertLocked
  suffix: Random, laser carbine, Alert Level Lock


# ===== Fills =====
- type: entityTable
  id: FillGunSafeRandomPistol
  table: !type:AllSelector
    children:
    - id: WeaponDislippler
    - id: GunpetInstrument
    - id: WeaponSniperMosin
