using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Orion.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ExperimentalDestructiveScannerMenu : FancyWindow
{
    public event Action? OnServerButtonPressed;
    public event Action? OnPerformPressed;

    public ExperimentalDestructiveScannerMenu()
    {
        RobustXamlLoader.Load(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        PerformButton.OnPressed += _ => OnPerformPressed?.Invoke();
    }

    private static string FormatServerName(string name)
    {
        const string prefix = "RND-Server";
        if (!name.StartsWith(prefix, StringComparison.Ordinal))
            return name;

        var suffix = name[prefix.Length..].TrimStart();
        return string.IsNullOrWhiteSpace(suffix)
            ? Loc.GetString("research-server-name-base")
            : Loc.GetString("research-server-name-with-suffix", ("suffix", suffix));
    }

    public void UpdateState(ExperimentalDestructiveScannerBoundInterfaceState state)
    {
        ServerLabel.Text = state.ConnectedServerName == null
            ? Loc.GetString("research-machine-common-server-none")
            : Loc.GetString("research-machine-common-server-current", ("name", FormatServerName(state.ConnectedServerName)));

        InsertedItemLabel.Text = Loc.GetString("research-machine-common-labeled-value",
            ("label", Loc.GetString("research-machine-experimental-destructive-scanner-status")),
            ("value", state.InsertedItem ?? Loc.GetString("research-machine-common-none")));

        OperationsContainer.RemoveAllChildren();
        foreach (var experiment in state.Experiments)
        {
            OperationsContainer.AddChild(BuildExperimentEntry(experiment));
        }

        if (state.Experiments.Count == 0)
        {
            OperationsContainer.AddChild(new Label
            {
                Text = Loc.GetString("research-machine-experimental-destructive-scanner-operations-empty"),
                Modulate = Color.Gray,
            });
        }

        var result = string.IsNullOrWhiteSpace(state.LastResult)
            ? Loc.GetString("research-machine-common-none")
            : state.LastResult;

        var lastOperation = new FormattedMessage();
        lastOperation.AddText(Loc.GetString("research-machine-common-labeled-value",
            ("label", Loc.GetString("research-machine-common-last-result")),
            ("value", result)));
        LastOperationLabel.SetMessage(lastOperation);
    }

    private Control BuildExperimentEntry(ResearchMachineExperimentUiData experiment)
    {
        var headerLabel = new RichTextLabel();
        var headerMessage = new FormattedMessage();
        headerMessage.AddMarkupOrThrow($"[color=lightblue]{FormattedMessage.EscapeText(experiment.Name)}[/color]");
        headerLabel.SetMessage(headerMessage);

        var progressText = Loc.GetString("research-machine-experiment-progress",
            ("objective", experiment.Objective),
            ("progress", experiment.Progress),
            ("target", experiment.Target));

        var descriptionLabel = new RichTextLabel
        {
            HorizontalExpand = true,
            MaxWidth = 620,
        };
        var descriptionMessage = new FormattedMessage();
        descriptionMessage.AddText(experiment.Description);
        descriptionLabel.SetMessage(descriptionMessage);

        var progressLabel = new RichTextLabel
        {
            HorizontalExpand = true,
            MaxWidth = 620,
        };
        var progressMessage = new FormattedMessage();
        progressMessage.AddMarkupOrThrow($"[color=lightgray]{FormattedMessage.EscapeText(progressText)}[/color]");
        progressLabel.SetMessage(progressMessage);

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 2,
            Margin = new Thickness(6),
            RectClipContent = true,
            Children =
            {
                headerLabel,
                descriptionLabel,
                progressLabel,
            },
        };

        return new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#23232A"),
                BorderColor = Color.FromHex("#4A4A56"),
                BorderThickness = new Thickness(1),
            },
            Children = { content },
        };
    }
}
